###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "cliente1@gmail.com",
    "password": "123456"
}

//shakirboca@gmail.com --> Cliente
//martingalvano@gmail.com --> Mozo
###
GET http://localhost:3000/auth/logout
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiJmYTBjM2Y0Mi03NmFkLTQ4NjEtOWVkNS1iZWQ4NGU1N2IyOTIiLCJlbWFpbCI6Imp1YW5jaXRvUGVyYXpAZ21haWwuY29tIiwidGlwb1VzdWFyaW8iOiJBZG1pbmlzdHJhZG9yIiwiaWF0IjoxNzUyNjEzNTE0LCJleHAiOjE3NTI2MTQ0MTR9.DfTdF63CL9YpPLnOOAp4zAQX3D01bDdF3XkEB82OwG4

###
POST http://localhost:3000/auth/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiJmYTBjM2Y0Mi03NmFkLTQ4NjEtOWVkNS1iZWQ4NGU1N2IyOTIiLCJlbWFpbCI6Imp1YW5jaXRvUGVyYXpAZ21haWwuY29tIiwidGlwb1VzdWFyaW8iOiJBZG1pbmlzdHJhZG9yIiwiaWF0IjoxNzUyNjE0NDE0LCJleHAiOjE3NTI2MTUzMTR9.V1_L-0sOmo5SLqYRWG2QqCNnJ5JXjpQNBCMeDxDpicw