###
GET http://localhost:3000/clientes/

###
GET http://localhost:3000/clientes/id/4a8f3e67-827d-442d-8a04-7beb453133ea

###
POST http://localhost:3000/clientes/
Content-Type: application/json

{
    "nombreUsuario": "Jope",
    "contrasenia": "123456",
    "nombre": "Jose",
    "apellido": "Chaya",
    "fechaNacimiento": "21/08/2004",
    "telefono": "3415324728",
    "email": "jope@gmail.com"
}

###
PATCH http://localhost:3000/clientes/id/4a8f3e67-827d-442d-8a04-7beb453133ea
Content-Type: application/json

{
    "nombre": "franco nicolas"
}