###
GET http://localhost:3000/clientes/

###
GET http://localhost:3000/clientes/id/991bd649-5fea-48e9-8062-e3cd12d0bb4d

###
POST http://localhost:3000/clientes/
Content-Type: application/json

{
    "nombreUsuario": "Test4",
    "contrasenia": "123456",
    "nombre": "Fernanda",
    "apellido": "Pepe",
    "fechaNacimiento": "21/08/2004",
    "telefono": "3415324728",
    "email": "test4@gmail.com"
}

###
PATCH http://localhost:3000/clientes/id/21169869-1cd2-45ea-a962-d3b48f665599
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiIyMTE2OTg2OS0xY2QyLTQ1ZWEtYTk2Mi1kM2I0OGY2NjU1OTkiLCJlbWFpbCI6ImNsaWVudGUxQGdtYWlsLmNvbSIsInRpcG9Vc3VhcmlvIjoiQ2xpZW50ZSIsInVzZXJuYW1lIjoiY2xpZW50ZTEiLCJpYXQiOjE3NTU3ODAxMzksImV4cCI6MTc1NjM4NDkzOX0.HFQRO6T5gRXsuXw5_D0Rw1OyqCHe2-DQMJg191OKzoA
Content-Type: application/json

{
    "nombre": "franco nicolas"
}