###
POST http://localhost:3000/novedades
Content-Type: application/json

{
    "titulo": "Nasdasdasdas",
    "descripcion": "ajasfafsdafasdadasdf",
    "fechaInicio": "2025/07/25",
    "fechaFin": "2025/08/25"
}

###
PATCH http://localhost:3000/novedades/update/43
Content-Type: application/json

{
    "titulo": "aaaaaaaaaaaa",
    "descripcion": "aaaaaaaaaaaaaaa",
    "fechaInicio": "2025/07/25",
    "fechaFin": "2025/08/25"
}