### Por parte del Cliente
POST http://localhost:3000/pedidos/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiIwZGM4ZDVjZi04ZTI5LTQzNmItOTVhNS1mNTUyYTA1MzY3NDgiLCJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsInRpcG9Vc3VhcmlvIjoiQ2xpZW50ZSIsInVzZXJuYW1lIjoiVGVzdDIiLCJpYXQiOjE3NTU2MTExMTEsImV4cCI6MTc1NjIxNTkxMX0.o71-CnSzNTC_AOPlXntAdG_0SxWDVhjKkF5p-DDkT-o
Cookie: e185e54f-e7c2-4931-aefe-6b3605e0096d

{
    "order": {
        "cantidadCubiertos": 4,
        "observacion": "Pan sin gluten",
        "items": [
            {
            "nombre": "Pan Sin TAC",
            "tipo": "Postre",
            "monto": 5000.00,
            "cantidad": 4
            },
            {
            "nombre": "Hamburguesa con queso",
            "tipo": "Plato_Principal",
            "monto": 12000.00,
            "cantidad": 2
            }
        ]
    }
}

### Por parte del Cliente NO registrado
POST http://localhost:3000/pedidos/
Content-Type: application/json 
Cookie: 17134ce5-d71b-494d-ba32-999bf44a0906

{
    "order": {
        "cantidadCubiertos": 3,
        "observacion": "Flan con dulce de leche",
        "items": [
            {
            "nombre": "Pan Sin TAC",
            "tipo": "Postre",
            "monto": 150.25,
            "cantidad": 4
            },
            {
            "nombre": "Flan",
            "tipo": "Postre",
            "monto": 2000,
            "cantidad": 2
            }
        ]
        
    }
}

### Por parte del Mozo
POST http://localhost:3000/pedidos/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiI5OTAyM2M2Mi05YjY2LTQxYTMtYWFjMi1jODU3MDk5ZmQ1NzMiLCJlbWFpbCI6ImZyYW5jb25pY29sYXNAZ21haWwuY29tIiwidGlwb1VzdWFyaW8iOiJNb3pvIiwidXNlcm5hbWUiOiJmcmFuY29uaWNvbGFzIiwiaWF0IjoxNzU1NjA3NjE4LCJleHAiOjE3NTYyMTI0MTh9.MqukPxFbUks8dqBIIUCECjNZ1FjnTp5mjhBckap1FJ4

{
    "tableNumber": 1,
    "order": {
        "cantidadCubiertos": 4,
        "observacion": "Flan y Pan caseros",
        "items": [
            {
            "nombre": "Empanada de Carne",
            "tipo": "Entrada",
            "monto": 7000,
            "cantidad": 1
            }
        ]
    }
}