###
GET http://localhost:3000/productos

###
GET http://localhost:3000/productos/id/3

###
GET http://localhost:3000/productos/nombre/Empanada

###
GET http://localhost:3000/productos/tipoProducto/Bebida
###
POST http://localhost:3000/productos/
Content-Type: application/json

{
    "nombre": "Empanada Capresse",
    "descripcion": "Flan casero con dulce de leche y caramelo.",
    "estado": "Disponible",
    "tipo": "Postre",
    "esVegetariana": true,
    "esVegana": false,
    "esSinGluten": false
}   

###
PATCH http://localhost:3000/productos/id/3
Content-Type: application/json

{
    "nombre": "Coca-Cola Zero",   
    "estado": "No_Disponible"
}