###
POST http://localhost:3000/qr/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiIzODIzZjZjOC1kYTUzLTRkMWMtYTE4Ny03NGFkYjIyMzFjOTciLCJlbWFpbCI6Impvc2VicHBAZ21haWwuY29tIiwidGlwb1VzdWFyaW8iOiJNb3pvIiwidXNlcm5hbWUiOiJKb3NlQl8yMDA0IiwiaWF0IjoxNzU5MzQzNTI3LCJleHAiOjE3NTkzNDM3MDd9.ZYPeVpcjGDlm9UDSX4DRMuS4_1EiDzTpK3X4LIhgYDU

{
    "tableNumber": 1
}

###
GET http://localhost:3000/qr/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiI4ZTA2ZTRiOS1jYzU4LTRmZWEtOWQ2ZS04MThjZmQ1Zjg2ZjciLCJlbWFpbCI6InNoYWtpcmNoYXlhMjAwNUBnbWFpbC5jb20iLCJ0aXBvVXN1YXJpbyI6Ik1vem8iLCJ1c2VybmFtZSI6Im1vem8iLCJpYXQiOjE3NTkyNDQ5MDksImV4cCI6MTc1OTI0NTA4OX0.S-8kx0tdzg-Xyf5PL6eHC4wMSTF34GWssdbL2C-ZP2c

{
    "tableNumber": 5
}
