###
GET http://localhost:3000/mesas/

###
GET http://localhost:3000/mesas/capacidad/4

###
POST http://localhost:3000/mesas/
Content-Type: application/json

{
    "capacidad" : 4
}

###
DELETE http://localhost:3000/mesas/nromesa/6