###
GET http://localhost:3000/mozos

###
GET http://localhost:3000/mozos/id/9ae3b11b-f8ff-4a1e-ac7d-2867dbcf77ff

###
GET http://localhost:3000/mozos/nombre/Herlaumarsan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiIzYTIwMDQyNS0zYTU2LTRmYWEtYTA3Yy1lY2UwYjdkMmFjZWQiLCJlbWFpbCI6Im1hcnRpbmdhbHZhbm9AZ21haWwuY29tIiwidGlwb1VzdWFyaW8iOiJNb3pvIiwidXNlcm5hbWUiOiJIZXJsYXVtYXJzYW4iLCJpYXQiOjE3NTUyNjkzNzAsImV4cCI6MTc1NTg3NDE3MH0.Q_1_SvJYatPlXhRCf76JbzxxQl0FReAv6h8PpcPLPbc

###
POST http://localhost:3000/mozos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiJlNTM0YjUyMS1iNzEwLTRhNjQtOGUyOC1iMTZkMTY5ZDVlYjQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInRpcG9Vc3VhcmlvIjoiQWRtaW5pc3RyYWRvciIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3NTU2MDk2MzEsImV4cCI6MTc1NjIxNDQzMX0.56jCQ5DHfhVtDWciHrmX6b1WWK12rbIiLx3AfLQ5p48

{
    "nombreUsuario": "example3",
    "contrasenia": "holamundo",
    "nombre": "Shakir",
    "apellido": "Barragan Landriel",
    "dni": "11222555",
    "telefono": "34asc",
    "email": "example3@gmail.com"
}   

###
PATCH http://localhost:3000/mozos/id/3a200425-3a56-4faa-a07c-ece0b7d2aced
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiIzYTIwMDQyNS0zYTU2LTRmYWEtYTA3Yy1lY2UwYjdkMmFjZWQiLCJlbWFpbCI6Im1hcnRpbmdhbHZhbm9AZ21haWwuY29tIiwidGlwb1VzdWFyaW8iOiJNb3pvIiwidXNlcm5hbWUiOiJIZXJsYXVtYXJzYW4iLCJpYXQiOjE3NTUyNjkzNzAsImV4cCI6MTc1NTg3NDE3MH0.Q_1_SvJYatPlXhRCf76JbzxxQl0FReAv6h8PpcPLPbc
Content-Type: application/json

{
    "nombre": "Franco Nicolás"
}

###
DELETE http://localhost:3000/mozos/id/c8c5405b-101c-4d89-8714-01ef9b2a69a0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiJlNTM0YjUyMS1iNzEwLTRhNjQtOGUyOC1iMTZkMTY5ZDVlYjQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInRpcG9Vc3VhcmlvIjoiQWRtaW5pc3RyYWRvciIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3NTU2MDk2MzEsImV4cCI6MTc1NjIxNDQzMX0.56jCQ5DHfhVtDWciHrmX6b1WWK12rbIiLx3AfLQ5p48
