###
GET http://localhost:3000/mozos

###
GET http://localhost:3000/mozos/id/9ae3b11b-f8ff-4a1e-ac7d-2867dbcf77ff

###
GET http://localhost:3000/mozos/nombre/Herlaumarsan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiIzYTIwMDQyNS0zYTU2LTRmYWEtYTA3Yy1lY2UwYjdkMmFjZWQiLCJlbWFpbCI6Im1hcnRpbmdhbHZhbm9AZ21haWwuY29tIiwidGlwb1VzdWFyaW8iOiJNb3pvIiwidXNlcm5hbWUiOiJIZXJsYXVtYXJzYW4iLCJpYXQiOjE3NTUyNjkzNzAsImV4cCI6MTc1NTg3NDE3MH0.Q_1_SvJYatPlXhRCf76JbzxxQl0FReAv6h8PpcPLPbc

###
POST http://localhost:3000/mozos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiIzNzE2YmMxMy1jY2JkLTQ1MDctYWYzZS04OTQ0YmEzYzE3MDQiLCJlbWFpbCI6Im5pY29sYXNtYXp6YWdsaWFAZ21haWwuY29tIiwidGlwb1VzdWFyaW8iOiJBZG1pbmlzdHJhZG9yIiwiaWF0IjoxNzU0NDE4NTExLCJleHAiOjE3NTQ0MTkxMTF9.DuGxRplTZkchFrlPiiKRt4ft3fWTxdjmuSVSqmfn2H0

{
    "nombreUsuario": "shakirboca05",
    "contrasenia": "holamundo",
    "nombre": "Shakir",
    "apellido": "Barragan Landriel",
    "dni": "46132659",
    "telefono": "3413151500",
    "email": "shakirboca05@gmail.com"
}   

###
PATCH http://localhost:3000/mozos/id/3a200425-3a56-4faa-a07c-ece0b7d2aced
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiIzYTIwMDQyNS0zYTU2LTRmYWEtYTA3Yy1lY2UwYjdkMmFjZWQiLCJlbWFpbCI6Im1hcnRpbmdhbHZhbm9AZ21haWwuY29tIiwidGlwb1VzdWFyaW8iOiJNb3pvIiwidXNlcm5hbWUiOiJIZXJsYXVtYXJzYW4iLCJpYXQiOjE3NTUyNjkzNzAsImV4cCI6MTc1NTg3NDE3MH0.Q_1_SvJYatPlXhRCf76JbzxxQl0FReAv6h8PpcPLPbc
Content-Type: application/json

{
    "nombre": "Franco Nicolás"
}

###
DELETE http://localhost:3000/mozos/id/d701b3f5-477c-41cd-b453-5606d25ce8b0
