###
GET http://localhost:3000/productos

###
GET http://localhost:3000/productos/id/15

###
GET http://localhost:3000/productos/nombre/tarta
###
GET http://localhost:3000/productos/tipo/plato_principal
###
POST http://localhost:3000/productos/
Content-Type: application/json

{
    "nombre": "Salchicha con papa",
    "descripcion": "Con carne, lechuga y tomate",
    "estado": "Disponible",
    "tipo": "Plato_Principal",
    "esSinGluten": false,
    "esVegetariana": true,
    "esVegana": false,
    "esAlcoholica": false
}

###
PATCH http://localhost:3000/productos/actualizarProducto/1
Content-Type: application/json

{   
    "categoria": "Comida",
    "datos": {
        "esSinGluten": false,
        "esVegana": false,
    }
}

###
DELETE http://localhost:3000/Productos/eliminarProducto/15
